---
- name: Register the node with core
  ansible.builtin.import_tasks: node_docker_register.yml
  tags:
    - node_docker_register

- name: Run eru-agent
  ansible.builtin.import_tasks: node_docker_agent.yml
  tags:
    - node_docker_agent
