---
- name: Install the etcd cluster
  hosts: etcd
  become: true
  roles:
    - role: etcd
      tags:
        - etcd

- name: Install core
  hosts: core
  become: true
  roles:
    - role: core
      tags:
        - core

- name: Register the docker nodes
  hosts: node_docker
  become: true
  roles:
    - role: node_docker
      tags:
        - node_docker
