---
- name: Install the etcd cluster
  hosts: etcd
  become: true
  roles:
    - role: etcd
      tags:
        - etcd

- name: Install core, its resource plugins and the cli
  hosts: core
  become: true
  roles:
    - role: core
      tags:
        - core
    - role: plugins
      tags:
        - plugins
    - role: cli
      tags:
        - cli

- name: Register the containerd nodes
  hosts: node_containerd
  become: true
  roles:
    - role: node_containerd
      tags:
        - node_containerd

- name: Register the process nodes
  hosts: node_process
  become: true
  roles:
    - role: node_process
      tags:
        - node_process


- name: Register the cocoon nodes
  hosts: node_cocoon
  become: true
  roles:
    - role: node_cocoon
      tags:
        - node_cocoon
