#!/bin/bash
# Date: 2017-9-13
# Usage: deploy eru-core, eru-agent in one node
#        and run eru-lambda for example

# yum
./yum.sh

# docker
./docker.sh

# etcd
./etcd.sh

# start etcd then start docker
systemctl enable etcd
systemctl start etcd
systemctl enable docker
systemctl start docker

# calico
./calico.sh

# eru
mkdir -p /etc/eru/tls
./core.sh
./agent.sh

# pod and node
# simulate 2C 0.5G
etcdctl set /eru-core/pod/test/info '{"name":"test","desc":"lambda testing","favor":"CPU"}'
etcdctl set /eru-core/pod/test/node/${HOSTNAME}/info "{\"name\":\"${HOSTNAME}\",\"endpoint\":\"tcp://127.0.0.1:2376\",\"podname\":\"test\",\"public\":false,\"available\":true,\"cpu\":{\"0\":10,\"1\":10},\"memcap\":536870912}"
CAPEM=`cat /etc/docker/tls/ca.crt`
KEYPEM=`cat /etc/docker/tls/client.key`
CERTPEM=`cat /etc/docker/tls/client.crt`
etcdctl set /eru-core/pod/test/node/${HOSTNAME}/ca.pem " ${CAPEM}"
etcdctl set /eru-core/pod/test/node/${HOSTNAME}/key.pem " ${KEYPEM}"
etcdctl set /eru-core/pod/test/node/${HOSTNAME}/cert.pem " ${CERTPEM}"

# run lambda test
./lambda.sh