---
- name: Pull cli image
  ansible.builtin.command: "docker pull {{ core_cli_image }}"
  changed_when: true

- name: Create a temporary cli container
  ansible.builtin.command: "docker create --name eru-cli-installer {{ core_cli_image }}"
  register: core_cli_create
  changed_when: core_cli_create.rc == 0
  failed_when: core_cli_create.rc != 0 and 'already in use' not in core_cli_create.stderr

- name: Copy the eru-cli binary out of the image
  ansible.builtin.command: docker cp eru-cli-installer:/usr/bin/eru-cli /usr/local/bin/eru-cli
  changed_when: true

- name: Remove the temporary cli container
  ansible.builtin.command: docker rm -f eru-cli-installer
  changed_when: true
