- name: add golang repo
  apt_repository:
    repo: ppa:longsleep/golang-backports
    state: present

- name: add go and cli into $PATH
  lineinfile:
    path: /etc/profile
    line: PATH=$PATH:/usr/local/go/bin:/root/go/bin

- name: install golang
  unarchive:
    src: https://dl.google.com/go/go1.17.linux-amd64.tar.gz
    dest : /usr/local
    remote_src: yes

- name: install cli
  shell: GO111MODULE=on /usr/local/go/bin/go install github.com/projecteru2/cli@latest
