---
- name: Ensure the resource plugin directory
  ansible.builtin.file:
    path: "{{ core_plugin_dir }}"
    state: directory
    mode: '0755'

- name: Render the core config
  ansible.builtin.template:
    src: core.yaml.j2
    dest: "{{ eru_config_dir }}/core.yaml"
    mode: '0644'
  notify: Restart core
