---
- name: Install the core binary
  ansible.builtin.import_tasks: core_binary.yml
  tags:
    - core_binary

- name: Generate core's ssh key pair
  ansible.builtin.import_tasks: core_ssh.yml
  tags:
    - core_ssh

- name: Configure core
  ansible.builtin.import_tasks: core_config.yml
  tags:
    - core_config

- name: Launch core
  ansible.builtin.import_tasks: core_launch.yml
  tags:
    - core_launch
