---
- name: Download etcd release
  ansible.builtin.get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/{{ etcd_basename }}.tar.gz"
    dest: "/tmp/{{ etcd_basename }}.tar.gz"
    mode: '0644'

- name: Extract etcd release
  ansible.builtin.unarchive:
    src: "/tmp/{{ etcd_basename }}.tar.gz"
    remote_src: true
    dest: /tmp/

- name: Install etcd binaries
  ansible.builtin.copy:
    src: "/tmp/{{ etcd_basename }}/{{ item }}"
    remote_src: true
    dest: "/usr/bin/{{ item }}"
    mode: '0755'
  loop:
    - etcd
    - etcdctl
  notify: restart etcd
