---
- name: Install etcd binaries
  ansible.builtin.import_tasks: etcd_binary.yml
  tags:
    - etcd_binary

- name: Configure etcd
  ansible.builtin.import_tasks: etcd_config.yml
  tags:
    - etcd_config

- name: Launch etcd
  ansible.builtin.import_tasks: etcd_launch.yml
  tags:
    - etcd_launch
