---
- name: Reload sshd
  ansible.builtin.systemd:
    name: ssh
    state: reloaded

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart the agent
  ansible.builtin.systemd:
    name: "{{ node_cocoon_agent_service }}"
    daemon_reload: true
    state: restarted
