yavirt_image: harbor.shopeemobile.com/cloud/yavirt:{{ yavirt_image_tag }}
yavirt_bin: /opt/yavirt-deploy/bin
yavirt_run: /opt/yavirt-deploy/run
node_yavirt_name: "{{ inventory_hostname | regex_replace('\\.', '-') }}"
