---
- name: Install docker
  ansible.builtin.import_tasks: docker_install.yml
  tags:
    - docker_install

- name: Configure docker
  ansible.builtin.import_tasks: docker_config.yml
  tags:
    - docker_config

- name: Launch docker
  ansible.builtin.import_tasks: docker_launch.yml
  tags:
    - docker_launch
